### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by pwalczyszyn** [0x80/firebase-tools-with-isolate#13]
Hi, I'm trying to setup fresh new project. And I'm running into some auth issues. From the same monorepo I'm able to deploy hosting app, but functions app is failing with following error:
```
FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at responseToError (/Users/piotr/Projects/my-project/node_modules/.pnpm/firebase-tools-with-isolate@13.16.0_encoding@0.1.13/node_modules/firebase-tools-with-isolate/lib/responseToError.js:49:12)
    at RetryOperation._fn (/Users/piotr/Projects/my-project/node_modules/.pnpm/firebase-tools-with-isolate@13.16.0_encoding@0.1.13/node_modules/firebase-tools-with-isolate/lib/apiv2.js:303:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to get Firebase project adembed-app. Please make sure the project exists and your account has permission to access it.
```

I already reauthenticated with CLI firebase app.

**Comment by pwalczyszyn** [comment]
I sorted it out by doing `npx firebase login` from my functions folder.
