### ISSUE TITLE
Isolation failed: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zallesov** [0x80/firebase-tools-with-isolate#16]
Hi. I've been using firebase-tools-with-isolate for a while now.
Switched to it from @rxdi/firelink
Both solutions seem like a workaround. But Google does not seem to want to support monorepo setups for cloud functions at any point. 

Recently I start to get an error for any deployment attempt

```
i  functions: Isolation failed: Maximum call stack size exceeded

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
```

 firebase-debug.log
```
[info] i  functions: preparing . directory for uploading... 
[info] i  functions: Isolate the source 
[error] i RangeError: Maximum call stack size exceeded
    at file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1076:56
    at Array.filter (<anonymous>)
    at listInternalPackages (file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1076:49)
    at file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1078:22
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1077:59)
    at file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1078:22
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1077:59)
    at file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1078:22
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1077:59)
    at file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1078:22
    at Array.flatMap (<anonymous>)
    at listInternalPackages (file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1077:59)
    at file:///Users/zallesov/Projects/mult.dev/air/node_modules/.pnpm/isolate-package@1.20.0/node_modules/isolate-package/dist/index.mjs:1078:22
```
      
isolate.config.json
```
   {
  "logLevel": "debug",
  "workspaceRoot": "../",
  "buildDirName": "dist"
}

```
   
tsconfig.json
```
   {
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "A backend service",
  "extends": "./base.json",
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,
    "noEmitOnError": true,
    "skipLibCheck": true,
    "strict": true,
    "outDir": "dist",
    "lib": [
      "esnext"
    ],
    "sourceMap": true,
    "types": [
      "node"
    ]
  }
}
```

   I have switched to the latest version `13.27.0`
   I have over 10 packed in my monorepo. But even if I disable all but one the issue remains.
   I've also tried clean install. No change. Even those that worked before are now broken
   I use pnpm

**Comment by 0x80** [comment]
@zallesov sounds to me like you might have some sort of circular dependency going on? I can't think of another reason. I suggest checking your internal dependencies declarations in the manifests to see if you can spot the mistake.

In the meantime also deploying with a single firebase config in the root is now supported, so if anything I think that should simplify your setup. See [this](https://github.com/firebase/firebase-tools/issues/653#issuecomment-2585895455) for more into

I'm going to close this for now. Please try the new setup and feel free to re-open it if you still run into issues.

**Comment by benedelstein** [comment]
I had this issue because I accidentally named my package.json "firebase-functions" which collided with firebase's own package, causing infinite recursion. Check if your package name collides with any dependency name?

**Comment by 0x80** [comment]
@benedelstein Aha thanks for the tip! I'll reopen it to add some sort of fix at some point...
